sudo: false
dist: trusty
language: php

env:
  global:
  - COMPOSER_ARGS="--no-interaction"
  - WOOCOMMERCE_RELEASES_FILE=${TRAVIS_BUILD_DIR}/.bin/shop-releases.txt
 
matrix:
  allow_failures:
    - stage: acceptance-test
  include:
  - php: 5.6
    if: type != cron AND env(PHRASEAPP_PULL) != '1'
  - php: 7.0
    if: type != cron AND env(PHRASEAPP_PULL) != '1'
  - php: 7.1
    if: type != cron AND env(PHRASEAPP_PULL) != '1'
  - php: 7.2
    if: type != cron AND env(PHRASEAPP_PULL) != '1'

  - stage: get-woocommerce-versions
    if: type = cron
    php: 7.2
    install: skip
    before_script: skip
    script: bash .bin/get-woocommerce-versions.sh
    after_script: skip
    after_failure: skip
      
  - &acceptance-test
    stage: acceptance-test
    if: type != cron
    php: 7.2
    env: 
    - GATEWAY=API-TEST
    - WOOCOMMERCE_NUMBER=1
    before_install:
    - travis_retry composer self-update 
    install:
    - export WOOCOMMERCE_VERSION=$(awk "NR==${WOOCOMMERCE_NUMBER} {print; exit}" ${WOOCOMMERCE_RELEASES_FILE})
    - echo "Testing with Woocommerce version ${WOOCOMMERCE_VERSION}" 
    - bash .bin/generate-release-package.sh test
    - travis_retry composer require --dev $COMPOSER_ARGS codeception/codeception:^2.5
    - travis_retry composer install $COMPOSER_ARGS
    - composer show
    script: bash .bin/run-ui-tests.sh
    after_script: skip
    after_success: skip
#    - bash .bin/upload-logs-and-notify.sh
    after_failure: skip
#    - bash .bin/upload-logs-and-notify.sh fail
  - <<: *acceptance-test
    env:
    - GATEWAY=API-TEST
    - WOOCOMMERCE_NUMBER=2
  - <<: *acceptance-test
    env:
    - GATEWAY=API-TEST
    - WOOCOMMERCE_NUMBER=3
  - <<: *acceptance-test
    env: 
    - GATEWAY=API-WDCEE-TEST
    - WOOCOMMERCE_NUMBER=1
  - <<: *acceptance-test
    env:
    - GATEWAY=API-WDCEE-TEST
    - WOOCOMMERCE_NUMBER=2
  - <<: *acceptance-test
    env:
    - GATEWAY=API-WDCEE-TEST
    - WOOCOMMERCE_NUMBER=3
  - <<: *acceptance-test
    env: 
    - GATEWAY=NOVA
    - WOOCOMMERCE_NUMBER=1
  - <<: *acceptance-test
    env:
    - GATEWAY=NOVA
    - WOOCOMMERCE_NUMBER=2
  - <<: *acceptance-test
    env:
    - GATEWAY=NOVA
    - WOOCOMMERCE_NUMBER=3

  - stage: phraseapp-pull
    if: type != cron AND env(PHRASEAPP_PULL) = '1'
    language: ruby
    ruby: 2.5.3
    before_install: skip
    install:
    - travis_retry gem install bundler -v 2.0.1
    - travis_retry bundle install
    script:
    - .bin/rake phraseapp:ci_update
    after_script: skip

  - stage: phraseapp-check-if-in-sync
    if: type = pull_request
    language: ruby
    ruby: 2.5.3
    before_install: skip
    install:
    - travis_retry gem install bundler -v 2.0.1
    - travis_retry bundle install
    script:
    - .bin/rake phraseapp:ci_check_if_in_sync
    after_script: skip
  
  - stage: deploy
    if: tag IS present AND type = push
    language: php
    php: 7.1
    before_install: skip
    install:
      - travis_retry composer install $COMPOSER_ARGS
      - rvm install 2.5.3
      - travis_retry gem install bundler -v 2.0.1
    after_install: skip
    before_script: skip
    script: skip
    after_script: skip
    before_deploy:
      - export REPO_NAME=`echo $TRAVIS_REPO_SLUG | awk -F'/' '{print $2}'`
      - export RELEASE_NOTES=$(composer make-release-notes)
      - bash .bin/generate-wiki-notes.sh
      - bash .bin/generate-readme-badge.sh
      - bash .bin/update-internal-readme-and-php.sh
      - bash .bin/generate-release-package.sh $TRAVIS_TAG
    deploy:
      provider: releases
      github_token: ${GITHUB_TOKEN}
      api_key: ${GITHUB_TOKEN}
      file: woocommerce-wirecard-ee.zip
      name: "${REPO_NAME} ${TRAVIS_TAG}"
      body: "${RELEASE_NOTES}"
      skip_cleanup: true
      on:
        repo: ${TRAVIS_REPO_SLUG}
        tags: true
    after_deploy: 
#      svn checkout is not producing logs, not to oerload travis, so wait for 30 minutes till the checkout completes
      - travis_wait 60 bash .bin/upload-to-marketplace.sh
      - export TMPDIR=/tmp/wirecard
      - git clone -b master --depth 1 https://$WIRECARD_CEE_GITHUB_TOKEN@github.com/$DEPLOYMENT_PROJECT $TMPDIR
      - cd $TMPDIR && travis_retry bundle install
      - bin/rake trigger_build

before_install:
  - export PHPCS_DIR=/tmp/phpcs
  - export SNIFFS_DIR=/tmp/sniffs
  - git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR
  - git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $SNIFFS_DIR
  - $PHPCS_DIR/bin/phpcs --config-set installed_paths $SNIFFS_DIR

install:
  - travis_retry composer require --dev $COMPOSER_ARGS satooshi/php-coveralls:^1.0
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

script:
  - composer cs-check

after_script:
  - travis_retry composer upload-coverage
  - bash .bin/generate-tag.sh

notifications:
  email: false
  slack:
    rooms:
      secure: YI7sUrfMyKyJD60kElGkO7yBDkGEh+069yS8bFAIDUST7s48J+dDP/r2G9dN9oQwhs9hvNjpNytpZDPys838T+Z0mNtFZ9Wu022hV3MpbKUuMl7L9P0MQQmxjg4bKyKK3Hl9tPrZ3UsKRlwIUmRGGYQ7cjs4zumorqs19YsB3X+WnnxAmmYB3kHQYfNKgVnmcG2QHJyx5KaLZ0EsWynSHXkYb8bVCtdlbQFNnpChvGHPprZrHAszLCYnlU7AEZGdbuk17oIfXO9Wjuu1GV8iJ2VgKkTCzW4FBC5eHJyZezojPFUm1I5tvdihRZuyBekVGOF23J6pvHLqPx77clT+/Vn6T+UMDuh1INZ0LKt4UOU42oEDKGblWZx2VYWcHwfEK+ckJWZkT9EBfg/CMenJly2tbtBj6++XNvxgGEDn6XqKIEatcb7X/aiy4f8BPXa3/pzgZAlvzZbGGqHFNZPAlgcXBBXgbaC7VvMhvi6Z5AG5ylKzPS5GCD95ozPC+cGv0234TBJus5oZck4qNiT53IUQ7Ta+OGVB0Mea105VAoQI0I7YcgaqW6c4h2YTmnuuQsIzAwPOrJ5TAinj8Z8mZ9C11tEcNF3Pgy1tOoG/YLurhOJm7v1ebotRb/DIeSHU8RfNatnDSSky4YS6Y8k2pQthdC9m7m2f2mJYuGdLjlM=
    template:
      - "%{repository}#%{build_number} (%{branch} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    on_success: change
    on_failure: change
