webserver:
   container_name: "${WOOCOMMERCE_CONTAINER_NAME}"
   build: .
   environment:
    WORDPRESS_DB_PASSWORD: "${WOOCOMMERCE_DB_PASSWORD}"
   links:
    - dbserver:mysql
   ports:
    - 9090:80

dbserver:
   container_name: woo_mariadb
   image: mariadb
   environment:
    MYSQL_ROOT_PASSWORD: "${WOOCOMMERCE_DB_PASSWORD}"
   ports:
    - 3307:${WOOCOMMERCE_DB_PORT}
