name: Validate PR name

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: wirecard/checkout@v2.0.0
        with:
          ref: ${{ github.head_ref }}
      - name: Validate PR branch name
        uses: brkicadis/pr-lint@master
        with:
          branch: ${{ github.head_ref }}
          regex: '^(RC-(([0-9])+\.){2}([0-9])+-(patch|minor|major))$'
      - name: Check files
        run: ls
