name: Validate PR name

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR branch name
        uses: brkicadis/pr-lint@master
        with:
          branch: ${{ github.head_ref }}
