name: PR lint

on: pull_request

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: seferov/pr-lint-action@master
      with:
        title-regex: '^RC-(([0-9])+\.){2}([0-9])+-(patch|minor|major)'
