name: Bump versions and add initial CHANGELOG entry

on:
  pull_request:
    types: opened

jobs:
  change-version:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'RC-')
    name: Change release version
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: wirecard/checkout@v2.0.0
        with:
          ref: ${{ github.head_ref }}
      - name: Get tags
        run: git fetch --prune --unshallow
      - name: Bump versions and add entry to CHANGELOG
        id: check-version
        uses: wirecard/extension-release-info-update-action@master
        with:
          repository: ${{ github.event.repository.name }}
          action: initial_changelog_and_version_update
      - name: Set global git conf
        run: git config --global user.email "" && git config --global user.name "github-actions"
      - name: Commit files
        run: git commit -m "Bump versions and add initial changelog entry" -a
      - name: Push changes
        uses: wirecard/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
